### ISSUE TITLE
De-deprecate "runtime"

### ISSUE THREAD

**Issue by AkihiroSuda** [compose-spec/compose-spec#101]
**What is the problem you're trying to solve**
Allow using third party runtimes such as Kata Containers and gVisor

**Describe the solution you'd like**
Remove "_DEPRECATED_: this attribute is low-level platform implementation detail" from `runtime`: https://github.com/compose-spec/compose-spec/blob/master/spec.md#runtime

**Additional context**
`runtime` was ported from compose v2 and marked as "DEPRECATED" in https://github.com/compose-spec/compose-spec/commit/ce585a8cb35e98ffe10a48f73bc05ef86b85a722#diff-958e7270f96f5407d7d980f500805b1bR1193 (#78 )

Previous discussion: https://github.com/docker/compose/issues/6239 (closed by the stale bot)

**Comment by AkihiroSuda** [comment]
PR: #102

**Comment by EricHripko** [comment]
From what I understand, the reasoning behind marking this as deprecated was because its a non-portable/low-level setting that is arguably better placed elsewhere rather than `compose.yml`. Given that this is attribute is still supported, what's the goal of de-deprecating this?

**Comment by AkihiroSuda** [comment]
>  elsewhere 

where?

**Comment by EricHripko** [comment]
In the Compose implementation itself. Please also note that Compose implementations are [not required to implement all the attributes](https://github.com/compose-spec/compose-spec/blob/master/spec.md#requirements-and-optional-attributes). I think we can summon @ndeloof for additional context around this attribute.

**Comment by ndeloof** [comment]
> to ensure it to be supported permanently
supporting this attribute will be a decision by Compose implementations

The reason for deprecation is indeed that this exposes a low-level implementation detail that hardly make sense in a compose high-level application description. 

The `runtime` attribute only exists to support legacy approach to enable Nvidia GPUs, which required to replace `runc` with a custom runtime. This is obsolete today with container hooks support in engine and `--gpu` option (see https://docs.docker.com/config/containers/resource_constraints/#gpu). Within compose file format, we are discussing a proposal to add GPU support [here](https://github.com/compose-spec/compose-spec/pull/100)

**Comment by AkihiroSuda** [comment]
This proposal is for supporting Kata and gVisor, not for supporting GPUs

**Comment by ndeloof** [comment]
ok then
:+1:

**Comment by EricHripko** [comment]
Is this something that makes sense as a machine-wide setting? Cannot think off top of my head of an example where one would want to mix-and-match containers running using different runtimes (would this work at all?)

**Comment by AkihiroSuda** [comment]
gVisor has non-trivial issues on performance and compatibility, so `runtime: gvisor` is mostly expected to set only for non-DB containers.

**Comment by EricHripko** [comment]
Thanks for sharing this insight 👍
