### ISSUE TITLE
investigate support for init container

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#11]
**What is the problem you're trying to solve**
init container(s) run before service container in sequence and can prepare environment. Think "containerized entrypoint"

We might want to support such init containers in compose spec, with obvious mapping for Kubernetes

**Describe the solution you'd like**
syntax proposal and lifecycle document

**Additional context**
See https://github.com/docker/compose/issues/6855

**Comment by acran** [comment]
To throw in just another idea (based on the example from @hangyan above):
~~~yml
version: "3"
services:
  web:
    build: .
    depends_on:
      - db
      - redis
  redis:
    image: redis
    depends_on:
      init_container:
        condition: service_finished_successfully
  init_container:
      image: busybox
      command:  ping www.google.com
  db:
    image: postgres
~~~

I.e. introduce a new enum value (`service_finished_successfully`) to the `depends_on` condition such that the dependent service will only start after the other service exited with a successful exit code - or just exited at all (`service_finished`).
See https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on and #72

**Comment by mikesir87** [comment]
I actually just came across this use case, but I'll admit my first approach/thought was to do it as outlined by @acran. The `depends_on` already supports some of part of this use case, so adding another enum value makes sense. It also aligns with how ECS thought about it (can't deep-link onto the page, but see the `dependsOn` section [in their task definition parameters](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html)).

**Comment by EricHripko** [comment]
I like the suggestion from @acran 👍 It seems like a natural extension of Compose language.
