### ISSUE TITLE
Investigate v2 support

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#12]
**What is the problem you're trying to solve**
Docker compose file format version 2.x is still in use by many people
And only differ from v3 by a few removed attribute + addition of `deploy`

**Describe the solution you'd like**
spec could accept 2.x format. Maybe oculd also reconsider some of the removed attributes for inclusion in v3. excluded attribute would then be documented but flagged as Deprecated

**Comment by SuperSandro2000** [comment]
I heavily rely on ``extends`` and the limits for mem and cpu so leaving 2.x out of the spec is a big bummer for me.

**Comment by agners** [comment]
@ndeloof hm, `device_group_rules` is missing from the above list. Have you generated that list somehow? What was your base?

**Comment by ndeloof** [comment]
I made this list from a diff between schema versions (updated with a few missing ones)

The main point in this issue is not to make an exhaustive list of missing attributes, but to debate if we want to adopt this approach to resurect them. On agreement we could then actually introduce them in the spec with fixes comparable to #63

`extends` being a special case, we probably will have to discuss this legacy feature separately

**Comment by agners** [comment]
@ndeloof thanks for the list update!

I guess there are two steps, discussing reintroduction of v2 options, and actually introduce them. Is your idea to introduce them to the spec in one go or just have a single issue (this one) to discuss which ones to introduce?

There are actually quite some options. I more and more think it will be hard to do introduce/discuss them in union likely will take a long time to sort out things out and come to an agreement.

How about we group them a bit, and create separate issues for each group?

Resource constraints:

* `blkio_config`
* `cpu_count` :
* `cpu_percent`
* `cpu_shares`
* `cpu_period`
* `cpu_quota`
* `cpu_rt_period`
* `cpu_rt_runtime`
* `cpus` :
* `cpuset`
* `mem_limit`
* `memswap_limit`
* `mem_swappiness`
* `mem_reservation`
* `oom_kill_disable`
* `oom_score_adj`
* `pids_limit`

Devices

* `device_cgroup_rules`
* `devices`

Network
* `dns_opts`

Volume/Storage

* `storage_opt`
* `volume_driver`
* `volumes_from`

Others
* `group_add`
* `platform`
* `runtime`
* `scale` (replaced by `replicas`?)
* `extends` (*)

**Comment by ndeloof** [comment]
This is really about discussing reintroduction of v2 options. List was most to illustrate the diff. Actual execution will be driven by our decision.

I can see 3 categories:
1. legacy attribute which still make sense on top of plain docker engine, but not supported in v3 due to Docker Swarm influence.
2. legacy attribute with an alternative in v3 format (scale vs replica)
3. load-time `entends` features

(1) can be defined in the spec/schema, maybe marked as deprecated (can be the subject for further discussions)
(2) can be easily supported as a field relocation
(3) is more a pre-processing question. docker-compose never opened the Pandora box of yaml templating and I don't think we should, but this can be debated separately.


I'd like we avoid a "per attribute" discussion, and look for agreement on just embracing our legacy and consider all v2 format as "supported by the spec" whenever (as anything else) Compose implementations might just ignore or reject them. This is a prerequisite for #13

**Comment by agners** [comment]
I guess there is also a 1.5: Legacy attribute which still make sense on top of plain docker engine, but would go into a different location for v3 format. Point in case: `blkio_config`, something which now probably needs to go under `resources` `limits`. There are also some which there is a v3 attribute, but the semantic changed (maybe `replicas` is actually of that variant).

Here is my attempt:

(1)
* `cpu_period` 
* `cpu_rt_period`
* `cpu_rt_runtime`
* `oom_kill_disable`
* `oom_score_adj`
* `device_cgroup_rules`
* `dns_opts`
* `storage_opt`
* `volume_driver` 
* `volumes_from` (probably should be marked depricated as the top level volume with name is preferred in v3).
* `group_add`
* `platform`
* `runtime`

(1.5)
* `blkio_config`: should probably  go into `resources` `limits` `blkio`, with field relocation for legacy attribute `blkio_config`.
* `cpu_count` : should probably go into `resources` `limits` `cpu_count`
* `pids_limit` : should probably go into `resources` `limits` `pids`


(2)
* `cpu_percent` (just other semantics than `cpus`)?
* `mem_limit` :  (`resources` `limits` `memory`)
* `mem_reservation`:  (`resources` `reservations` `memory`)
* `scale` (`deployment` `replicas`, are the semantics really the same?)

(3)
* `extends`

Not yet categorized, further research needed:

* `cpus` : (v3 claims part of `resources`, `resources` `limits` `cpus` ?)
* `cpu_shares` : (v3 claims part of `resources`, probably `resources` `reservations` `cpus`)?
* `cpu_quota` : (v3 claims part of `resources`, probably `resources` `limits` `cpus`)?
* `cpuset` : (v3 claims part of `resources`)?
* `memswap_limit` : (v3 claims part of `resources`)?
* `mem_swappiness` : (v3 claims part of `resources`)?

**Comment by ndeloof** [comment]
I suggest we define actions by categories, so we can agree on some and start execution. We can then debate which fields get into each category

(1) 
get re-introduced in the compose-spec schema and spec.md. As other fields in the spec, Compose Implementation MAY ignore them and SHOULD warn user if they're used in a compose.yaml file.

(1.5) 
get also re-introduced but marked as *deprecated* in the spec and JSON schema. 
We can investigate support in compose-go to magically relocate such fields to new canonical field if we can confirm the semantic didn't changed. 

(2) 
semantic to be confirmed by further investigation, if comfirmed same as 1.5
AFAIK `scale` == `deployment replicas`

(3) 
corner cases. Devil is in the details. Let's see how things goes and if we get some legacy fields left behind.

I've created https://github.com/compose-spec/compose-spec/issues/67 to debate `extends` which is a way more complex beast.

**Comment by ndeloof** [comment]
@justincormack @nebuk89 I suggest we select this one for next community meeting agenda, so we agree on adopting this approach

**Comment by EricHripko** [comment]
It seems like this is done now:
- We've decided to merge v2/v3
- We've merged the specs for these

Is there anything else remaining or should we close this as resolved?
