### ISSUE TITLE
Feature parity 2.4

### ISSUE THREAD

**Issue by hholst80** [compose-spec/compose-spec#123]
**What is the problem you're trying to solve**
 
Make sure 2.4 functionalities are mappable to 3.x functionality.

**Describe the solution you'd like**

A feature matrix with everything mentioning that it only works in compose 2.4 with mapping or support to 3.x

**Comment by EricHripko** [comment]
Hi @hholst80 - thank you for suggesting this idea 👍 I believe this is addressed already as Compose Spec is a superset of v2 and v3 (see https://github.com/compose-spec/compose-spec/issues/12). Is there specific functionality that's still missing?

**Comment by hholst80** [comment]
It looks like most of my old concerns have been addressed in 3.9 compose spec.  Would you agree @EricHripko ?

If so, a feature mapping matrix would be fairly redundant as the only non-1:1 option needing any kind of nontrivial mapping would be the scale parameter. And it is mentioned explicitly to be deprecated and mapped to deployment replicas.

**Comment by EricHripko** [comment]
I think so, yes 👍
