### ISSUE TITLE
Don't require version

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#13]
**What is the problem you're trying to solve**
Better than being version-based, Compose spec should be feature driven

**Describe the solution you'd like**
As my compose file use some xyz attribute, I should not have to specify a version attribute, but just let the Compose implementation tell me this attribute is not supported.

**Comment by bfirsh** [comment]
I have no strong opinions about this, but some thoughts:

- The advantages are not explicit in this ticket or https://github.com/docker/compose/issues/7201. The one I can think of is that it is just one fewer thing for the user to thing about, which is good. Are there others?
- We originally added versions so we could cleanly make breaking changes. Without the ability to easily make (occasional) breaking changes, I'm concerned the format would accumulate cruft. You can make incremental non-breaking changes up to a certain point, but at some point you need to step back and refactor.
- From a user's point of view, it might be hard to figure out what Compose implementations you can use. If it was feature based, to get a Compose file working with a tool might be a frustrating game of removing features until it works, or trying to match up your file with a long list of features supported. Instead with versions, an implementation can say "supports v3.4" and you can be confident your Compose 3.4 file will work.

**Comment by ndeloof** [comment]
Breaking changes in the sense "_something than can't be disambiguated and require an explicit version_" didn't happend so far. v2 vs v3 removed fields (that could have been kept but ignored) and introduced `deploy`. But the semantic of existing fields didn't changed. We can live without Breaking changes in the sense we can forbid changing the semantic of an existing field. We can deprecate some, but they should still be valid for parsing, maybe ignored with or without a warning to end-user - we should make compose-go a good citizen for this purpose.

From a user point of view things are already confusing. none of docker-compose or swarm do fully support v3. From this PoV the v3 format is already subject to "_only consider fields you support, ignore or reject others_" policy. And version here is just useless. This is arguably not the case in v1/v2 if you only consider docker-compose tool, but then you would expect other implementation to support everything, which make it hardly portable to anything else but a local docker engine.

**Comment by bfirsh** [comment]
> We can live without Breaking changes in the sense we can forbid changing the semantic of an existing field.

This is what I mean by accumulated cruft. At some point the design may greatly benefit from a change in semantics of a field, for whatever reason, and by removing the version, this becomes difficult.

I was trying to look up the historical artifacts here. [Here is the PR that added versioning.](https://github.com/docker/compose/pull/2421) Unfortunately it nor the linked issues mention reasoning, so I'm going to have to use my fuzzy memory here.

To clarify the reason this was originally added, as far as I can remember: the version field was for _unknown_ future breaking changes (in an [unknown unknowns](https://en.wikipedia.org/wiki/There_are_known_knowns) sense).

Services used to be top-level keys. Versioning was added so we could move services under `services` and add a top-level `volumes`. This was sort of backwards compatible, in that you could detect the new structure, but it was real messy (what if you had a service called `services`?). We realised the backwards compatibility logic would be much cleaner with a version string, and this would protect us against future changes where it couldn't be backwards compatible.

I agree a version field is ugly. It would be nice for users not to have to worry about them. But, the downsides of the cruft seemed to outweigh the upside of being able to refactor the design of the file when needed, without version-detecting gymnastics.

This optimal decision here might be made if we can enumerate the advantages and disadvantages of having a version field.

**Comment by Toasterson** [comment]
An experience from the OpenZFS group is, that a feature based approach can work. But it needs solid base and a strategy for dealing with changes. Any grown spec will not be able to achieve this, unless one clear cut is made.

**Comment by ndeloof** [comment]
Benefits:
- no more confusion for end-users between v1, v2 and v3. Many thing "_v2 is for local, v3 is for cloud_" which demonstrate we made a mistake and need to reconcile both
- no need to use same version on compose files used as overrides
- no need to check version relevance for a feature. 
- features get rejected/ignored/disabled because version used in file is too low, whenever tool do support them. The fact `version: "3"` is same as `3.0` exhacerbate this issue

Drawbacks:
- user can't check if his tool do support xyz; but by actually testing it with a compose file. We might include in the spec, for each defined element, a list of tools supporting it (could be just small badges for known tools) + a compatibility matrix page
- we can't just decide `foo` which used to define feature X will now target independent feature Y. Will need either to define a new field, or alternate value syntax if relevant.
- we can't drop legacy fields. But we still can mark them as Deprecated, and offer common mitigation code within compose-go for go-based tools.

To avoid too much cruft being added, I've suggested https://github.com/compose-spec/compose-spec/issues/17 so it is easier to experiement and we establish as a governance rule that no new feature should be introduced if not actually supported by _at least_ two Compose Implementation. Typically this would prevent major changes like v3 to happen without a full cross-cloud story behind, but still would allow tools to accept `x-mycloud-autoscale` without an error, so that MyCloud Inc can move forward and propose changes to the spec with some concrete usage examples. 

Remember that, today, none of Compose implementation do fully support v3.* format: docker-compose just ignores `deploy` and `stack deploy` targetting swarm miss support for a large set of v3 fields. Also, docker-compose is the sole one to fully support all v2 fields assuming, but still as some of them depend on actual runtime (linux/windows, user namespace enabled, ...) a compose file still may not be usable by a user, even if version is ok.

Version used to be a simple way for docker-compose to confirm input file was valid and fully supported, as the sole implementor for this format. With more tools relying on the same format, and many of them not able to support all features, we need a more flexible approach.

Illustration sample : docker-compose was [updated](https://github.com/docker/compose/pull/7217) to support v3.8 without actually any new feautre added, just don't fail when users adopted this version - probably as they also deploy on Swarm/Kubernetes, or maybe just used latest published version according to docs.

AFACIT version was introduced to make it easier distinguish v1 vs nested structure defined in v2, as first time a significant structural change was introduced in compose file format. But on the other hand it is feasible to distinguish them without a version key, as both formats don't overlap. I assume this first need to introduce structural changes suggested breaking changes might be necessary at some point, and as such versionning would hep.

It _might_ happen the semantic of a field would benefit some changes. But I can see many places docker-compose already addressed such issues by supporting alternate field format (typically: short notation string vs nested struct), and for the benefits of the user is the semantic is significantly distinct, then a distrinct field with would be a better choice imho, whenever this require to find an alternate name. This typically happened on Moby API with volume vs bind vs mount.

**Comment by EricHripko** [comment]
If we think that there can never be breaking changes, then let's dump the version from the spec. It's a bit of a gamble, but it looks like it's been fine so far due to the nature of Docker ecosystem.

I do agree that spec versions (as they exist today) aren't very useful. Mostly users just copy-paste `.yaml` from an example - spreading an arbitrarily chosen version through the codebase. No one really gives it any thought unless CLI tooling complains at them due to version being too low (for the desired feature) or too high (if tooling is too old).

**Comment by EricHripko** [comment]
> we can't drop legacy fields. But we still can mark them as Deprecated, and offer common mitigation code within compose-go for go-based tools.

what's the rationale behind this?

**Comment by justincormack** [comment]
@bfirsh as we still dont require every implementation to support all the features, "version 3.4" doesn't currently tell you everything you need to know...

**Comment by EricHripko** [comment]
One interesting thing is that absence of version currently means _version 1_. Removing version requirement would mean either:
- Deprecating _version 1_ since there's no feasible way to opt for it now
- Rehashing the schema for _version 1_ to allow for a top-level `version: ` attribute that can be used as a marker

**Comment by EricHripko** [comment]
In terms of conversion from _version 1_ to the latest _versionless_ version, it seems like it'd be a two-step process in most cases:
- Add top-level `services: ` key
- Indent the rest of the file one-level more

Depending on how much of v2 functionality makes it, users may also have to specify `version: '2.X'`.

**Comment by ndeloof** [comment]
We can detect v1 schéma on loading by the absence of 'services'. And if by chance a v1 compose file use this name for a container we still can detect schema mismatch.

I.e "try to load as v2 m. On failure fallback to v1 and convert"
As you noticed v1 format can be converted on the fly to v2/v3 without major efforts.

**Comment by omeid** [comment]
I think not requiring a version generally ends up acclimating endless cruft or just making versions merely implicit.

I understand that the way compose went about versioning was fundamentally flawed, for example the v2 for local and v3 for cloud you point out, but I am not sure needs to be necessarily the case going forward.

From the discussion it looks like making changes is what is being considered, so can you please explain what is the drawbacks of having versions versus "feature based implicit versioning"?

**Comment by ndeloof** [comment]
Today, when you select a version (assuming you know what they actually mean and not just copy paste from various sources) you assume your tool will support it. Which is wrong: many attributes will be rejected or ignored. Both for local and cloud.
There's no such thing like a compose implementation to support everything for v3.8. you'll always have to give it a try (we should recommend all implementation to offer a 'validate' or 'dry run' mode)

So this proposal is to get your tool to report features you expressed in your compose file it doesn't support.

**Comment by EricHripko** [comment]
> We can detect v1 schéma on loading by the absence of 'services'.

Oh - didn't think of that, that's an awesome idea 🙌 Incorporated this into this draft PR: https://github.com/docker/compose/pull/7459

**Comment by omeid** [comment]
A validation feature that reports what is supported is very helpful indeed, however if a compose implementation does not support everything in 3.8 spec, it is a bad implementation and should not be encouraged.

The proposition that the spec should allow partial implementation and forgo versioning is problematic. It will allow for an endless matrix of feature set and implementations that will force people to either stick to a specific implementation rendering the spec useless or force them to use the lowest common denominator of features, which is equally regressive.

**Comment by ndeloof** [comment]
> if a compose implementation does not support everything in 3.8 spec, it is a bad implementation and should not be encouraged.

3.8 schema do include both cluster-focussed features (like `replicas`, `placement`...) and others that only make sense for a local engine (like sharing namespaces, direct device binding, access to host resources...). So no existing implement do cover both of them. Benefit of compose spec is that it allows to cover both needs with a single config format and make an app (at least partially) portable.

Since v3 there's no such thing like a compose tool that covers all the compose file format features.

**Comment by omeid** [comment]
> Benefit of compose spec is that it allows to cover both needs with a single config format 

If I understand your argument correctly, it is no longer a single format, is it?

> make an app (at least partially) portable.

It is either portable or not, decades of Web Platform have taught us that partial portability is a recpie for accumlating craft, hacks, and unfortunate abstractions.
 
> Since v3 there's no such thing like a compose tool that covers all the compose file format features.
I have rarely used v3 due to missing features so I can't comment on that, but _what is_ does not need to be so.

I am interested to see how you think the issue of various implementations supporting different features is going to work in reality?

Is there an alternative to either sticking to a specific implementation and making the spec useless or only using the lowest common denominator of features?

**Comment by EricHripko** [comment]
It's important to highlight once again that none of Compose implementations today completely satisfy the latest `3.8` schema. The version statement simply overlooks the prerequisites/incompatibilities of individual features.

Whether a given feature is supported by Docker Swarm or local engine only is just one axis. The issue at hand spans beyond that. For example, Kubernetes implementations [don't support](https://github.com/compose-spec/compose-spec/issues/22) `depends_on` since their orchestrator simply works differently. Windows containers don't support *nix attributes like `shm_size`. These gaps are not (and I don't can be) addressed by the version statement.

In my view, what @ndeloof proposed earlier seems like the best (in terms of UX) approach:
> you'll always have to give it a try (we should recommend all implementation to offer a 'validate' or 'dry run' mode)

The tooling can validate the compose file and then either:
- reject it (Fail: cannot set `shm_size` on a Windows Container) or;
- warn about graceful fallback for some attributes (Ignore: `depends_on` has no effect on `kompose`)

This providers end user with a definitive answer on whether their `.yml` will work without descending into complex feature matrices.

**Comment by ndeloof** [comment]
> I am interested to see how you think the issue of various implementations supporting different features is going to work in reality?

Just as it does today: implementations would support attributes that are relevant for their target platform, and would reject or ignore others. In terms of UX, we should recommend to _at least_ warn user for unsupported attributes. Most compose-related tools today silently ignore unsupported attributes, which is bad IMHO.

**Comment by omeid** [comment]
What are some widespread tools that support the compose file, other than docker-compose and kompose?

**Comment by omeid** [comment]
> These gaps are not (and I don't can be) addressed by the version statement.

I understand your point, but there is no reason a baseline can not exist even with OS specific attributes while still allowing engines to implement _add-on_ features they want.

But one must be able to write a compose file, for a single node or multi-node cluster, based on a give version of the spec and expect it to work on every engine that supports that version, otherwise it is hard to call something an  _specification_ when it does not specify any requirements beyond a rough outline.

**Comment by EricHripko** [comment]
I agree that it makes sense to have a baseline - and it does somewhat exist today, as Compose spec defines a bunch of behaviors as 'MUST'. What would be the goal and benefits of versioning this baseline?

We've seen today that tooling that accepts version `3.8` of spec doesn't necessarily implement all the attributes. So why not just cut out the version and let the tooling inform end user what is and isn't supported?

**Comment by ndeloof** [comment]
> it is hard to call something an specification

The specification is here to define the expected behaviour for a Compose implementation regarding a set of specified attributes. For example, an implementation to support [`container_name`](https://github.com/compose-spec/compose-spec/blob/master/spec.md#container_name) has to conform to some specified rules regarding scalability and expected behaviour. This doesn't mean all Compose implementations MUST support this attribute - there might be some platform which don't have a matching concept - and then are allowed to ignore this attribute, as long as user can be informed.

So, by "Compose specification" we mean individual attributes are well specified, not that the whole compose features are required.

> ... expect it to work on every engine that supports that version

That would be ideal for end-user, but unfortunately doing so would require to limit the Compose specification to a very minimalist (then, useless) set of features, as target platform might not be based on Linux kernel namespaces.

**Comment by ndeloof** [comment]
Discussed and approved by community meeting on June 4th

**Comment by omeid** [comment]
> I agree that it makes sense to have a baseline - and it does somewhat exist today, as Compose spec defines a bunch of behaviors as 'MUST'. What would be the goal and benefits of versioning this baseline?

Changing the baseline.

**Comment by omeid** [comment]
> > ... expect it to work on every engine that supports that version.
>
> That would be ideal for end-user, but unfortunately doing so would require to limit the Compose specification to a very minimalist (then, useless) set of features, as target platform might not be based on Linux kernel namespaces.

There is no reason this has to be the case, you can have a specification that takes into account OS and Platform specific attributes without throwing out everything that isn't consistent across the board.

But looks like this shape has sailed now, so best of luck.

**Comment by elrac** [comment]
The first line of https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file is 

> The Compose file is a YAML file defining version (REQUIRED), services (REQUIRED), networks, volumes, configs and secrets.

Should that file have been changed to remove the (REQUIRED) after version?
