### ISSUE TITLE
Broken internal links in the spec

### ISSUE THREAD

**Issue by lenzls** [compose-spec/compose-spec#130]
In the "Compose file" section of the `spec.md`, internal links to the version, services, networks and volumes sections are broken.

**Comment by EricHripko** [comment]
Hi @lenzls 👋 Thanks for bringing this up - I can confirm that I'm seeing the same issue.

**Comment by lenzls** [comment]
Closing this, since the issue was fixed in https://github.com/compose-spec/compose-spec/pull/133.
