### ISSUE TITLE
--profile attribute not respected during 'down'

### ISSUE THREAD

**Issue by cunninghamd** [compose-spec/compose-spec#143]
**What is the problem you're trying to solve**
I have a set of services that I'd like to generally be "always on", with a subset that I'd like to restart as needed.

Each of these commands works as expected:
`docker-compose --profile web up -d` // starts services associated with "web" profile -- works fine
`docker-compose --profile infrastructure up -d` // starts services associated with "infrastructure" profile -- works fine

**Describe the solution you'd like**
I'd like this command:
`docker-compose --profile web down`
to only stop/remove services associated with the profile specified, i.e.: web.

**Additional context**
Love the possibility that profiles preset! Thanks for your hard work!

**Comment by EricHripko** [comment]
Hi @cunninghamd 👋 Thank you for sharing your feedback! Please note that this is a repo for Compose specification; the issue you're reporting seems to be about the tooling/particular implementation. Could you please suggest direct this to https://github.com/docker/compose instead?

**Comment by cunninghamd** [comment]
Will do, thanks!
