### ISSUE TITLE
pull_policy schema and spec differ

### ISSUE THREAD

**Issue by manthey** [compose-spec/compose-spec#158]
**What is the problem you're trying to solve**
The spec.md file states that `missing` is a valid value for `pull_policy`, but the schema does not list it in the enum.

**Describe the solution you'd like**
Either remove `missing` from `spec.md` or add it to `compose-spec.json` as a valid value for the `pull_policy` enum.

**Additional context**
I haven't checked if adding `missing` to the enum is sufficient for support in docker-compose.

**Comment by EricHripko** [comment]
Hi @manthey 👋 Thank you for spotting this issue and bringing this up! Looks like `missing` was introduced as the preferred alias for `if_not_present` in https://github.com/compose-spec/compose-spec/pull/136, but the change wasn't reflected in the spec.
