### ISSUE TITLE
pid_limit -> pids_limit

### ISSUE THREAD

**Issue by AkihiroSuda** [compose-spec/compose-spec#159]
**What is the problem you're trying to solve**

https://github.com/compose-spec/compose-spec/blob/167f207d0a8967df87c5ed757dbb1a2bb6025a1e/spec.md#pid_limit

`pid_limit` in the spec seems a typo of `pids_limit`, which was added in Docker Compose spec 2.1: https://github.com/docker/compose/commit/6a151aac046b18f4fe2ac46f79dc9c8ee83aa33a

**Describe the solution you'd like**

Change `pid_limit` to `pids_limit`

**Comment by ndeloof** [comment]
nice catch, thanks
