### ISSUE TITLE
Publicly published release versions of the specification(s)

### ISSUE THREAD

**Issue by JohnPreston** [compose-spec/compose-spec#171]
**What is the problem you're trying to solve**

As a developer I would like to be able to re-use the specification in my project and fetch the specification.
As of today, I would have to fetch it from `https://github.com/compose-spec/compose-spec/blob/master/schema/compose-spec.json` which comes from the master branch, and might change without notice.

Also this means I rely on Github availability to retrieve the schema programatically, which at times has proven to have down-time and could.

**Describe the solution you'd like**
Publish on release / new version of the specification, to a publicly available endpoint (can be AWS S3/ CloudFront or anything else really, just going with what I'd do) for all to fetch.

If semantic versioning is not planned to be used for publication, then when a new version is published, then maybe publish using the date as version ?

Thank you for your consideration.

PS: happy to publish it publicly myself, if you can just allow for a webhook to be set upon new change.

**Comment by EricHripko** [comment]
Hi @JohnPreston 👋 Thank you for suggesting this idea! There's a PR in flight (https://github.com/compose-spec/compose-spec/pull/164) trying to establish a release process for the spec. Could you check it out and add any feedback you might have there? I expect that the PR linked might be able to address this suggestion 🙂
