### ISSUE TITLE
Bring back extends to v3?

### ISSUE THREAD

**Issue by wildone** [compose-spec/compose-spec#184]
**What is the problem you're trying to solve**
Is it possible to add extends back into v3?

**Describe the solution you'd like**
Would like to be able to define a bunch of boilerplate services and then extend them in other specs.

**Additional context**
Would be good to know reasons for not having it in v3 if it's so?
Currently works in v2. 
Yaml pointers are so ugly, keeping everything in one file is way complex, command line include is obscure.

**Comment by EricHripko** [comment]
Hi @wildone 👋 Thank you for sharing this feedback! [Compose spec](https://compose-spec.github.io/compose-spec/spec.html) actually merged the v2/v3 formats and made the `version:` attribute optional. Thus, you should be able to use `extends` the way you described already 🙂
