### ISSUE TITLE
Typo in spec.md: sha356

### ISSUE THREAD

**Issue by lmroil** [compose-spec/compose-spec#190]
**What is the problem you're trying to solve**
The documentation contains text that looks like a typo. It says `redis@sha356`.

**Describe the solution you'd like**
Replace sha356, which doesn't exist, with sha256, which is common.

**Comment by ndeloof** [comment]
please open a PR, so you would be granted the "contributor" role :P

**Comment by ndeloof** [comment]
fixed by https://github.com/compose-spec/compose-spec/pull/185
