### ISSUE TITLE
Unexpected behavior for volumes with external: true

### ISSUE THREAD

**Issue by haotuusa** [compose-spec/compose-spec#192]
In the specification 

> If set to true, external specifies that this volume already exist on the platform and its lifecycle is managed outside of that of the application. Compose implementations MUST NOT attempt to create these volumes, and MUST return an error if they do not exist.

I'm running docker-compose on Windows WSL2 Ubuntu 20.04, and if the named volumes don't already exist, instead of throwing an error as documented, it creates the volumes.

**Comment by EricHripko** [comment]
Hi @haotuusa 👋 Thank you for sharing this feedback. I'll assume that this is an issue of implementation not following the spec (unless one of `docker-compose` authors correct me CC @ndeloof @ulyssessouza). With this being an implementation issue, the appropriate repository for this would be either https://github.com/docker/compose or https://github.com/docker/compose-cli.

**Comment by ndeloof** [comment]
please indeed report this on github.com/docker/compose
