### ISSUE TITLE
Volumes explanation does not match code examples

### ISSUE THREAD

**Issue by mbrodala** [compose-spec/compose-spec#198]
**What is the problem you're trying to solve**
The spec section about `volumes` mentions volume and service names which are not present in the given code examples.

**Describe the solution you'd like**
Update the explanation to the names used in the code examples.

**Additional context**
None.

**Comment by EricHripko** [comment]
Hi @mbrodala 👋 Thank you for spotting this issue and putting together a fix - really appreciate it 🎉
