### ISSUE TITLE
Fix config name copy/paste typo in configs section

### ISSUE THREAD

**Issue by nathanweeks** [compose-spec/compose-spec#230]
In the Configs example, It looks like `server-certificate` should be `http_config` (probably a copy/paste bug from the Secrets section)

https://github.com/compose-spec/compose-spec/blob/f3bc7a465e9ef7310df3b92adf1d683a2d03df71/spec.md?plain=1#L2248

**Comment by ndeloof** [comment]
yes indeed, please open a pull-request to get this fixed :)
