### ISSUE TITLE
Ability to define secrets from environment variables

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#251]
**What is the problem you're trying to solve**
`secrets` can be defined from a file, but in some circumstances, short-lived secrets are actually exposed by platform as environment variables (typically, `GITHUB_TOKEN`). 
We should offer an opportunity for user to define a secret to be set from environment variable.

**Describe the solution you'd like**
```yaml
secrets:
  github_token:
    environment: GITHUB_TOKEN
```

**Additional context**
Ability to pass build time secrets, like `docker build --secret id=github_token,env=GITHUB_TOKEN` does

**Comment by EricHripko** [comment]
Agreed, it's be pretty awesome to be able to inherit some of the environment variables from the host in Compose 🙌
