### ISSUE TITLE
Spec inconsistency between ports short and long syntax on port range

### ISSUE THREAD

**Issue by asaintsever** [compose-spec/compose-spec#262]
**What is the problem you're trying to solve**
There is a discrepancy in the [ports](https://github.com/compose-spec/compose-spec/blob/master/spec.md#ports) section of the specification: the short syntax does not seem to support host port range only (e.g. something like "8080-8090:80") and it is even explicitly stated that "Host and container **MUST** use equivalent ranges."

But, on another hand, the long syntax does allow for such expression and it clearly appears in one of the given examples:
```
ports:
  - target: 80
    host_ip: 127.0.0.1
    published: 8000-9000
    protocol: tcp
    mode: host
```
Which is equivalent to short syntax "8000-9000:80". Such change has been introduced with PR https://github.com/compose-spec/compose-spec/pull/222

**Describe the solution you'd like**
As Docker CLI currently allows the use of host port range only via `-p <host port range>:<container port>` (and so Docker Compose), and to get a consistent short/long syntax in the spec, update short syntax documentation as follows:

* remove statement "Host and container MUST use equivalent ranges."
* update short syntax examples with a host port range entry ("9090-9099:80" for e.g.)

**Additional context**
Such clarification will allow to ask for host port range only support on Podman Compose (and so Podman) as it currently fails at starting a Compose manifest using such configuration (both Podman Compose and Podman fail with error _"Error: host and container port ranges have different lengths"_).

**Comment by EricHripko** [comment]
Hi @asaintsever 👋 Thank you for sharing this feedback!

**Comment by glours** [comment]
I just opened an [PR](https://github.com/compose-spec/compose-spec/pull/272) and remove some confusion around the format of `ports.published` attribut
