### ISSUE TITLE
platform: s/osx/darwin/

### ISSUE THREAD

**Issue by AkihiroSuda** [compose-spec/compose-spec#265]
**What is the problem you're trying to solve**

https://github.com/compose-spec/compose-spec/blob/a5cd401cbdca20f044d11a05707d206dbbacf22c/spec.md#platform

"osx" does not conform to the [GOOS convention](https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/internal/goos/zgoos_darwin.go) which is required by the [OCI Image Spec](https://github.com/opencontainers/image-spec/blob/v1.0.2/image-index.md)

**Describe the solution you'd like**

Change the string to "darwin"

**Comment by glours** [comment]
That's true if you're using Golang but it isn't regarding [Rust conventions](https://doc.rust-lang.org/std/env/consts/constant.OS.html) for example.
Currently most of the implementations of the spec are done in Go but we should keep the specification open to other languages.

**Comment by AkihiroSuda** [comment]
> That's true if you're using Golang but it isn't regarding [Rust conventions](https://doc.rust-lang.org/std/env/consts/constant.OS.html) for example. Currently most of the implementations of the spec are done in Go but we should keep the specification open to other languages.

Rust implementations have to follow the Go convention too, otherwise Rust implementations can't use YAMLs that are written for Go implementations.

Anyway, the Go convention is already officially adopted by the OCI Image Spec: https://github.com/opencontainers/image-spec/blob/v1.0.2/image-index.md

**Comment by EricHripko** [comment]
The only reference to `darwin` I could find in the linked repo is this line of code: https://github.com/opencontainers/image-spec/blob/8205360b72afd0613e3823bbf978117f78274bd1/schema/validator.go#L233

Is this what you're referring to?

**Comment by AkihiroSuda** [comment]
@EricHripko 

https://github.com/opencontainers/image-spec/blob/v1.0.2/image-index.md

> - **`os`** *string*
>  This REQUIRED property specifies the operating system.
> Image indexes SHOULD use, and implementations SHOULD understand, values listed in the Go Language document for [`GOOS`](https://go.dev/doc/install/source#environment).

The `GOOS` link above contains the list of the valid GOOS values such as "darwin"

**Comment by EricHripko** [comment]
Makes sense, thank you for sharing this 👍
