### ISSUE TITLE
Allow depends_on to be optional to use profiles to control which services to run in development vs production

### ISSUE THREAD

**Issue by nickjj** [compose-spec/compose-spec#274]
**What is the problem you're trying to solve**

We can't use profiles to enable specific services in development but not production when using `depends_on`. That's because the current spec doesn't allow `depends_on` to be optional. This means in practice profiles can't be used to enable specific services in different environments which is the goal of profiles based on its first sentence of the official documentation.

In practice this is a very big deal because in development you may want to use `postgres` and `redis` locally through Docker Compose but in production you may use managed cloud provider services for this. You could say our apps do have dependencies on these services but they are optional from Docker Compose's point of view.

I've already gone into a huge amount of detail about this in https://github.com/docker/compose/issues/9795 but here's a recap:

**Describe the solution you'd like**

Imagine this set up. This actually works with v2.10.2 because there's supposedly an unfixed bug but it turns out this bug is actually what folks have been wanting for years since profiles were available.

```yml
services:
  postgres:
    profiles: ["postgres"]
  redis:
    profiles: ["redis"]
  web:
    profiles: ["web"]
    depends_on: ["postgres", "redis"]
  worker:
    profiles: ["worker"]
    depends_on: ["postgres", "redis"]
  assets:
    profiles: ["assets"]
```

In development you can set this environment variable in an ` .env` file to start everything:

```export COMPOSE_PROFILES=postgres,redis,assets,web,worker```

In production you can set this instead:

```export COMPOSE_PROFILES=web,worker```

This would let you avoid running `assets` containers in production for various watchers and also take advantage of using your cloud provider's managed Postgres and Redis services because the local containers for those services don't need to run since the cloud provider's managed service will fulfill that dependency.

The above is a fantastic solution to let developers pick and choose which services to run. The problem is the current spec doesn't allow the above. Docker Compose will error out saying your dependent services aren't available.

One person opened an issue bringing that up and they want it fixed to be more inline with the spec stating it's confusing. Many alternative solutions were proposed in https://github.com/docker/compose/issues/9795, some of which were to use multiple docker-compose.yml files or introducing more complexity into Docker Compose with competing options like `COMPOSE_SERVICE_FILTER` to allow for services to be defined and always running commands with `--no-deps`. None of which are ideal or allow the desired behavior.

**A proposed solution**

We already have profiles which according to the docs states:

> Profiles allow adjusting the Compose application model for various usages and environments by selectively enabling services

What about adding a new `necessity: "optional"` property which defaults to `necessity: "required"` to `depends_on` so it can all work the same with profiles being explicit, or maybe `required: false` which defaults to `required: true`?  That's in my opinion the easiest solution and it's backwards compatible for the "fixed" behavior while giving people who have already depended on the "unfixed" behavior a way to use Docker Compose in the way v2 has allowed us to use since the beginning of the year.

I'd really like this to be implemented before https://github.com/docker/compose/issues/9795 is addressed. Otherwise Docker Compose v2 will introduce breaking changes with this fix since this unfixed behavior has been available since v2 was around which has been almost a year? It was even GA'd almost 6 months ago.

There is currently no workaround other than using `sed` and other tools to programmatically alter a `docker-compose.yml` file for each project before the project is upped. This has been a workaround I've used for years because it was the only way to get the desired behavior of disabling `depends_on` on a few services in production while still using a single `docker-compose.yml` file for all environments. It's hacky, cryptic, error prone and required for every project.

The proposed solution here fixes everything to where you can enable specific services in any environment while still being able to use `depends_on` optionally. It sticks to the goal of what profiles says it does based on its documentation and improves the quality of life for developers and overall improves the developer experience.

**Comment by laurazard** [comment]
Thanks for making the proposal @nickjj! I think speaking on behalf of the Docker Compose maintainers, we're alright with putting addressing https://github.com/docker/compose/issues/9795 on hold until a discussion can be had regarding the proposal and a decision is reached.

--------------------

That said:

My issue with the current (unfixed) behavior is that it's unclear. As you mentioned, and the other issue reflects, the situation where a service's dependencies are silently ignored when they are not assigned to the same profile the service that depends on them is potentially confusing, and quoting from the same docs:
> But keep in mind that docker compose will only automatically enable the profiles of the services on the command line and not of any dependencies. This means that all services the targeted service depends_on must have a common profile with it, be always enabled (by omitting profiles) or have a matching profile enabled explicitly
is not how profiles were meant to be used when initially implemented.

This proposal addresses my main issue with the current behavior, which is reverting the default behavior to a sane, explicit state -- by default, be explicit and fail if a service that's enabled by an active profile relies on dependencies that are not enabled by the same profile. That said, it feels weird to me to have "optional" dependencies, or dependencies that are not required. I wonder if there is some other phrasing/wording here that is more intuitive (this is also why I suggested addressing your specific need in another way, such as with `COMPOSE_SERVICE_FILTER`).

**Comment by nickjj** [comment]
Thank you Laura.

Maybe the wording of `necessity: "optional"` or `required: false` isn't ideal because if the dependency comes from either Docker Compose or an external service then it's not optional, it's still required.

If the proposal idea is valid then it comes down to figuring out how to name and describe this property right?

`external: true` which defaults to `external: false` maybe seems more descriptive? That word even came out naturally when typing the above sentence. It is what it is, an external source that's providing the dependency to the service. The word still implies the dependency is required, it's just resolved internally (Docker Compose) or externally (outside of Docker Compose).

The only thing I don't like about that is linking "internal" to "Docker Compose" isn't immediately clear. It might be close tho?

Also one thing to think about is future states too. I originally thought `necessity: "optional"` was more suitable than a `required` boolean in case future states were added, this would avoid breaking things and make the property more flexible but maybe this is a YAGNI scenario?

**Comment by Drachenfels** [comment]
My use case is a little bit different, in my case I have docker-compose that is used on production with an external cloud instance to connect to *BUT* in local env developers tend to work two different ways. Either by instantiating proxy to the cloud service or running local instance via generic docker image. This is not either `external` nor `necessity: optional`, I think the most accurate in such a case would be `alternative` and perhaps another one `skip`.

Example case study would be:
```
elasticsearch_proxy:
  image: santthosh/aws-es-kibana:latest
  profiles:
    - proxy

elasticsearch_local:
  image: elasticsearch/elasticsearch:lastest
  profiles:
    - local

api:
  depends_on:
    elasticsearch_local:
      condition: service_healthy
      alternative:
        - elasticsearch_proxy
      skip:
        - prod

  profiles:
    - local
    - proxy
    - prod
```

For `--profile prod` dependency is skipped.

For `--profile local` elasticsearch_local must be present.

For `--profile proxy` alternative elasticsearch_proxy is found and expected to take its place.

Perhaps `skip` could be more explicit with `skip_if_profile`.

**Comment by ndeloof** [comment]
IMHO it would make more sense following your example (simplified) to have:
```yaml
services:
  db:
    image: postgres
    profiles: ["dev"]
  web:
    profiles: ["web"]
    depends_on: ["db"]
```
.. and have ability for production deployment to _override_  the db service to refer to an external service - this concept is not yet supported in the compose specification, but I'd like to investigate more about it.
More to come in a few (assuming I get some time to work on it :P)

**Comment by nickjj** [comment]
Hi,

@laurazard Docker Compose v2.19.0 broke DD in relation to this issue due to introducing:
> Fixed a bug in the up command which should not silently ignore missing depends_on services.

Can you please revert that fix? This change introduces a backwards incompatible change which has no viable workaround and breaks everything if you are using `depends_on` and profiles for the last 18 months or so with the "unfixed" behavior.

In an earlier comment you mentioned the Docker Compose maintainers were ok with not introducing that fix until this issue has a way forward.

**Comment by ndeloof** [comment]
Profiles are nice to exclude some services from default config, typically for services being only used by `run`
To tweak the compose model for development, adding a development-only service and declaring a depends_on relation, you should better rely on a compose-dev.yaml override file

**Comment by nickjj** [comment]
In my opinion profiles are a much better solution than an override file.

It allows you to use a single docker-compose.yml file and then situationally run your containers by defining a single environment variable. This is so much better than trying to juggle multiple compose files for different environments or using a `docker-compose.override.yml` file which is ignored from version control that you only use in dev. You still run into issues with `depends_on` using the override file approach too (I used an override file for like 4 years prior to profiles).

**Comment by ndeloof** [comment]
>  profiles are a much better solution than an override file.

They have some benefits for sure, but target a distinct usage and have way lower flexibility. Profiles are not there to replace overrides

> you still run into depends_on problems with the override file approach

sure, `depends_on` role is to define a relation between services, which you expect Docker Compose to check. So if you introduce a new service in an override file this one should also tweak dependent services to introduce such a relation.

> only having to set a single environment variable to control which containers you want to run in each environment.

usability of override files is indeed challenging. In my original proposal for profiles, I suggested we auto-detect some `compose-<profile>.yaml` file and merge it with default model. Maybe we could resurrect this idea?

Back to you issue with a short terms solution, I guess we could either temporary relax this rule to only show a warning, and/or introduce `required` attribute in depends_on long syntax so you can explicitly opt-out for Compose to check your model (at your own risks)

**Comment by nickjj** [comment]
I'm game for a short term solution that allows the behavior to work as it did before until a long term solution is available. Throwing a warning until a new property is scoped out sounds good.
