### ISSUE TITLE
The Compose Specification - secrets - Long syntax - Missing information

### ISSUE THREAD

**Issue by spisarau** [compose-spec/compose-spec#276]
`target: The name of the file to be mounted in /run/secrets/ in the service's task containers. Defaults to source if not specified.`
From this string  is not clear what happen if I provide name of the file like this **/server.cert**. Will it store in memory or not.

**Comment by glours** [comment]
@spisarau 
There is an [issue](https://github.com/compose-spec/compose-spec/issues/161) to track this problem and a [PR](https://github.com/compose-spec/compose-spec/pull/281) is ready to clarify it.
Does it answer your question?

**Comment by glours** [comment]
Closed by #281
