### ISSUE TITLE
No UTS namespace option

### ISSUE THREAD

**Issue by evsasha** [compose-spec/compose-spec#277]
**What is the problem you're trying to solve**
No [UTS docker setting](https://docs.docker.com/engine/reference/run/#uts-settings---uts) in docker-compose.

**Describe the solution you'd like**
Аdd this option to the compose format.

**Additional context**
Related to docker/compose#8408
Related to docker/compose#3338

**Comment by EricHripko** [comment]
Hi @evsasha 👋 Thank you for sharing this feedback - this seems like a great addition for the spec!

**Comment by man4red** [comment]
I would like to see that option too
