### ISSUE TITLE
clarification of 'expose' format

### ISSUE THREAD

**Issue by nicks** [compose-spec/compose-spec#293]
**What is the problem you're trying to solve**
The spec currently defines an "expose" field.
https://github.com/compose-spec/compose-spec/blob/1eb16a20675324b35258b74b8375b48399893eab/spec.md?plain=1#L813

text:
> `expose` defines the ports that Compose implementations MUST expose from container.

The spec doesn't define the format of this field, so I'm wondering how I should interpret it!

**Describe the solution you'd like**
Is it expected to be the same form as the one in the Dockerfile reference?

https://docs.docker.com/engine/reference/builder/#expose

i.e., "<port-number> / <protocol>", assuming tcp if protocol is omitted?

If so, I guess we could copy and paste that text (or link to it)

**Comment by EricHripko** [comment]
Hi @nicks 👋 Great point - this is something the spec could define better.
