### ISSUE TITLE
Docs on https://docs.docker.com/ not synced with master branch

### ISSUE THREAD

**Issue by An1s9n** [compose-spec/compose-spec#299]
In reference documentation in [configs](https://docs.docker.com/compose/compose-file/#configs) section one line is missing, but in the current repository in master branch it exists, see [here](https://github.com/compose-spec/compose-spec/blame/master/spec.md#L469)

Probably synchronization between reference docs and this repo is broken and should be fixed

**Comment by glours** [comment]
As this is the upstream repository, I think this better to open this issue in the https://github.com/docker/docs repo

**Comment by An1s9n** [comment]
Ok :)
