### ISSUE TITLE
Require normalized project names

### ISSUE THREAD

**Issue by mbland** [compose-spec/compose-spec#311]
**What is the problem you're trying to solve**

compose-spec/compose-go#261 changed `docker compose` behavior to require normalized project names as input, instead of normalizing project names automatically. This landed in [compose-spec/compose-go v1.2.5](https://github.com/compose-spec/compose-go/releases/tag/v1.2.5) and [docker/compose v2.5.1](https://github.com/docker/compose/releases/tag/v2.5.1).

However, the current error message "... is not a valid project name" gives no indication why a name isn't valid. This is surprising for users whose previously working project names no longer work with newer versions of docker compose. The valid format also isn't yet documented anywhere.

**Describe the solution you'd like**

An update to the spec to document the valid format may be in order (unless there are issues with other implementations besides `docker compose` preventing that). Following that, possibly updates to:

- https://docs.docker.com/compose/reference/#use--p-to-specify-a-project-name
- https://docs.docker.com/compose/environment-variables/envvars/#compose_project_name
- https://docs.docker.com/engine/reference/commandline/compose/#use--p-to-specify-a-project-name

I've drafted a patch in the [update-project-name-spec branch of my mbland/compose-spec fork](https://github.com/compose-spec/compose-spec/compare/master...mbland:compose-spec:update-project-name-spec?expand=1). If the change is acceptable, I'd also be willing to update `WithName` from cli/options.go in the compose-spec/compose-go repo to expand upon the error message.

**Additional context**

- https://github.com/docker/compose/issues/9741#issuecomment-1444623933

**Comment by ndeloof** [comment]
your patch looks good to me, can you please create a PR ?
