### ISSUE TITLE
Unpredictable outcomes when setting `network_mode` and `networks`

### ISSUE THREAD

**Issue by laurazard** [compose-spec/compose-spec#322]
## Context

In the `service` level configuration, it's possible to configure both `network_mode` and `networks` attributes. The interaction between these attributes is not specified, and (as of today) produces unexpected behaviors in Docker Compose.

Possible combinations of these attributes are:

| network_mode | networks | expected result |
|----------------|----------|-----------------|
| host                  | -               | clear                   |
| host                  | yes           | ??                       |
| none                 | -               | clear                   |
| none                 | yes           | ??                       |
| service:[a]       | -               | clear                   |
| service:[a]       | yes           | ??                        |  

For a more concrete example, take the following Compose file:

```yaml
services:
  a:
    image: alpine
    command: ping c
    network_mode: service:b
    networks:
      - n
  b:
    image: alpine
    command: top
  c:
    image: alpine
    command: top
    networks:
      - n

networks:
  n:
```

Currently, Docker Compose does not reject this file. However, if one were to try to run this file, service `a` is not able to ping `c` due to it's configured `network_mode` (fails with `ping: bad address 'c'`). This is strange, unexpected behaviour – my containers are on the same network, why can't they talk to each other?

Other shortcomings are less convoluted but should still be addressed:
- setting `network_mode: host` and `networks` results, in Docker Compose, in an error being returned by the daemon (which makes sense, these aren't compatible options, but the resulting message can be confusing and we could address this from the start by telling the user that this configuration is invalid)
- setting `network_mode: none` and `networks` doesn't produce an error, but the `network_mode` is ignored and the container is granted networking anyway to the defined networks. These should also be incompatible options.

## Describe the solution you'd like
We could define multiple rules for how the different combinations of these options should interact (and I welcome discussion on that) but I think the clearest, most explicit way forward here is to define, in the Spec, that these are incompatible attributes, and implementations SHOULD reject configurations containing both.

I was going to start by just making a PR to the Spec to address this, but I thought explaining the need for this more clearly was a better 1st step (and maybe someone has better ideas on how to handle it).

**Comment by ndeloof** [comment]
yes, basically we should declare `network_mode` and `networks` to be mutually exclusive
(I don't think we can model this in the json schema)

**Comment by glours** [comment]
Thanks @laurazard for the situation summary, I agree we should be clear about the unexpected  network configuration. 
Feel free to open the PR(s) to improve this part (and implementation) 🙏

**Comment by laurazard** [comment]
> Also, I noticed this, which I bet we are not enforcing:

Ohh that's a good point. I'll make a not to look into those as well.

> (I don't think we can model this in the json schema)

Turns out it is possible (example):
```patch
diff --git a/schema/compose-spec.json b/schema/compose-spec.json
index c587125..59bce10 100644
--- a/schema/compose-spec.json
+++ b/schema/compose-spec.json
@@ -425,7 +425,15 @@
         "working_dir": {"type": "string"}
       },
       "patternProperties": {"^x-": {}},
-      "additionalProperties": false
+      "additionalProperties": false,
+      "allOf": [
+        {
+          "not": {
+            "type": "object",
+            "required": [ "network_mode", "networks" ]
+          }
+        }
+      ]
     },
 
     "healthcheck": {
```

The downside to this is then, if we want to provide a more meaningful message to the user when this fails (i.e. `...network_mode and networks are incompatible properties...` we need to add (a fair bit) of custom code. On the other hand, enforcing it in the schema is really cool because stuff like yaml language servers can consume the schema and validate Compose files as you're writing them (this is such a lifesaver for me writing Compose files).

**Comment by ndeloof** [comment]
That's a weird syntax, but ¯\\_(ツ)_/¯ 
(I miss you XML schema
```xml
<choice>
            <element name="network_mode"/>
            <element name="networks"/>
</choice>
```)

**Comment by laurazard** [comment]
Yeaaah. I looked into it a bit more but I think it's overkill and makes the code harder to understand, and messages returned from conditions like `not`, `oneOff`, `allOf` look like:
```
  - service.foo Must validate one and only one schema (oneOf)
  - service.foo Must not validate the schema (not)
  - service.foo: Must validate all the schemas (allOf)
```

which is incomprehensible 😅

**Comment by ndeloof** [comment]
right, better get code to validate this and keep json schema cover the basic model
