### ISSUE TITLE
Question: Docker watch ignore folders/files

### ISSUE THREAD

**Issue by jgutenplan** [compose-spec/compose-spec#345]
**What is the problem you're trying to solve**
https://docs.docker.com/compose/file-watch/#example
this page talks about ignoring files for the new watch feature. In the example it recommends to ignore the node_modules folder but does not give an example. How do I ignore for watch?

**Describe the solution you'd like**
An example of how to ignore files for watch in compose.yaml

**Additional context**
None

**Comment by laurazard** [comment]
@ndeloof

**Comment by ndeloof** [comment]
indeed. I created a PR to improve the docs
