### ISSUE TITLE
The `domainname` section is marked as TODO

### ISSUE THREAD

**Issue by technosophos** [compose-spec/compose-spec#35]
I just noticed that there was no issue for this, and thought I would file a tracking issue.

**Comment by nathanweeks** [comment]
Looks like the `domainname` section has meaningful text now?

**Comment by EricHripko** [comment]
Indeed - it appears to have a [description attached](https://github.com/compose-spec/compose-spec/blob/5260c1bc8ee5e93ce88412bb460924e9535d9080/spec.md#domainname). Will close as resolved, but do let me know if there's anything else on this.
