### ISSUE TITLE
About version (deprecated) in compose file

### ISSUE THREAD

**Issue by wushu037** [compose-spec/compose-spec#352]
File: [03-compose-file.md](https://docs.docker.com/compose/compose-file/03-compose-file/)

The documentation mentions: "The Compose file is a YAML file defining [version](https://docs.docker.com/compose/compose-file/04-version-and-name/) (DEPRECATED)."

`version` seems useful, why is it deprecated?

I'm sorry, but I didn't find anything in the "[Version and name top-level element](https://docs.docker.com/compose/compose-file/04-version-and-name/)" documentation that would **==strongly indicate==** that "version" is deprecated

**Comment by laurazard** [comment]
Hiya @wushu037 –

If you'd like some more context as to why we deprecated the `version` top level element, you can look through the following issues and discussion there:
- https://github.com/compose-spec/compose-spec/issues/13
- https://github.com/docker/compose/issues/7201

The reason that we specifically call out that the element is **deprecated** is that, as noted [in this part of the spec](https://github.com/compose-spec/compose-spec/blob/master/04-version-and-name.md#version-top-level-element):

```yaml
Top-level version property is defined by the specification for backward compatibility but is only informative.

A Compose implementation SHOULD NOT use this version to select an exact schema to validate the Compose file, but prefer the most recent schema at the time it has been designed.
```

So the `version` element isn't being used for anything while parsing the Compose file, and hence the deprecated warning.
