### ISSUE TITLE
Document Catalog Hierarchy Writing and Rendering Errors

### ISSUE THREAD

**Issue by wushu037** [compose-spec/compose-spec#357]
There are authoring errors and there are rendering errors. These errors are simple, but can make it difficult to distinguish the hierarchy of elements and will lead to not knowing how to write the configuration file.

Just take the docker compose file document as an example

1. [link services](https://docs.docker.com/compose/compose-file/05-services/)
There is an exception to the indentation of the directory here. But the source code is correct. Maybe it's a bug in the rendering of the web front-end application
![image](https://github.com/compose-spec/compose-spec/assets/61787040/4faeb0af-e330-4c53-9e2e-9993bfa81c92)

2. [link network](https://docs.docker.com/compose/compose-file/06-networks/)
The driver here is at a level above all the elements that follow as headers, such as host or none, yet in the subsequent code examples, it feels like they are actually at the same level. This is a clear contradiction
![image](https://github.com/compose-spec/compose-spec/assets/61787040/56127d02-6de5-4e53-9066-5b3798a19fba)

    The source code is just wrong,  driver is `###`, others are `####`

3. [link volume](https://docs.docker.com/compose/compose-file/07-volumes/)
Here there is a similar problem to `2`. The difference is that it has the correct source code, both `###`, yet the rendering hierarchy is wrong.
![image](https://github.com/compose-spec/compose-spec/assets/61787040/ae808b27-6e38-4f15-9a2e-38f75bbddc1c)

4. There are obvious problems with the rendering, other than the ones mentioned above.

    4-1  [Link Version](https://docs.docker.com/compose/compose-file/04-version-and-name/)
In this document, the source code for the title is: `Version top-level element`
However the rendering is:`Version and name top-level element` I know this is the name in the document outline
![image](https://github.com/compose-spec/compose-spec/assets/61787040/ce3709eb-fec9-42b7-b389-27c54ae701ef)

    4-2 The front-end always takes the title of the document outline as the first title of the document page and renders it as `h1`, while ignoring the title in the source code and not even bothering to render it.
The source code again always has `##` as the top-level title, as if there is no `#`.
So the front-end just renders h1 and the next layer is h3
Like here: https://docs.docker.com/compose/compose-file/05-services/
![image](https://github.com/compose-spec/compose-spec/assets/61787040/6eb6a9eb-a8ee-47c5-bc3a-ceaf065cc8b3)

    Why is this? It makes you think that there is some non-essential accommodation between the front-end developers and the documentation writers. This may have caused trouble.

**Comment by aevesdocker** [comment]
Thanks for raising the issue @wushu037. The docs team is aware of the rendering issues. We'll shortly be moving over from Jekyl to Hugo. We're hoping this will fix this issue.

**Comment by wushu037** [comment]
@aevesdocker Okay, It probably needs to be repeated that it's not only the rendering that's the problem, but also the title hierarchy in the source code.
