### ISSUE TITLE
Suggest adding the description of expose of compose

### ISSUE THREAD

**Issue by wushu037** [compose-spec/compose-spec#359]
File: [05-services.md](https://docs.docker.com/compose/compose-file/05-services/)

The description in the documentation is: 
"expose defines the ports that Compose implementations MUST expose from container. These ports MUST be accessible to linked services and SHOULD NOT be published to the host machine. Only the internal container ports can be specified."

However, by default, containers in the same bridged network will expose all ports to each other, even if expose is not configured.
So what is the real meaning of expose?

**Comment by aevesdocker** [comment]
Thanks for contributing @wushu037. Closing this issue as it has now been resolved!
