### ISSUE TITLE
Swarm specific settings in long form of secrets should be marked as such.

### ISSUE THREAD

**Issue by marcpa00** [compose-spec/compose-spec#387]
File: [05-services.md](https://docs.docker.com/compose/compose-file/05-services/)

In the `secrets` section, long syntax, `uid`, `gid` and `mode` elements are currently only for swarm services, but it is not explicitly stated.

Until issue [9648](https://github.com/docker/compose/issues/9648) is fixed in compose, the documentation is misleading.

Suggestion: add 

   (docker swarm only) 

in the description for "`uid` and `gid`" and "`mode`".

**Comment by aevesdocker** [comment]
Thank for contributing @marcpa00. Closing this issue as it has now been resolved
