### ISSUE TITLE
Compose specification -> Services top-level element -> links

### ISSUE THREAD

**Issue by luoxiaohi** [compose-spec/compose-spec#394]
File: [05-services.md](https://docs.docker.com/compose/compose-file/05-services/)

the [legacy version Compose file 3.x](https://docs.docker.com/compose/compose-file/compose-file-v3/#links) has a warning in `links` attribute, says 

> The `--link` flag is a legacy feature of Docker. ..., we recommend that you use ... instead of using `--link`. 

but the [Compose specification](https://docs.docker.com/compose/compose-file/05-services/#links) doesn't have a warning in `links` attribute, seems to be in normal use. 

so, is `links` attribute deprecate or not ?

Thanks.

**Comment by aevesdocker** [comment]
Thanks for contributing @luoxiaohi. Closing this issue as it has now been resolved
