### ISSUE TITLE
Recent Commits Not Adhering to CONTRIBUTING.md

### ISSUE THREAD

**Issue by otkd** [compose-spec/compose-spec#400]
**What is the problem you're trying to solve**

Hi, I've noticed that some of the recent contributions to [`master`](https://github.com/compose-spec/compose-spec/commits/master/) have been signed off with pseudonyms instead of real names. This appears to be inconsistent with the project's contribution guidelines, as outlined in [`CONTRIBUTING.md`](https://github.com/compose-spec/compose-spec/blob/a215043336998402639b3085ea9d1758b085bb2e/CONTRIBUTING.md?plain=1#L116).

**Describe the solution you'd like**

Given maintainers do not seem to follow this requirement, I am wondering if this represents an oversight or if there has been a shift in the official contribution requirements for this project.

Could someone please clarify if this guideline is still in effect? And if so, could we possibly address the inconsistencies in the recent commits to ensure that all contributions comply with the established standards?

If there has been an official shift in contribution requirements, it might be helpful to update `CONTRIBUTING.md` to reflect the new policy.

**Additional context**

Examples of commits in question:

- a215043336998402639b3085ea9d1758b085bb2e
- 55b450aee50799a2f33cc99e1d714518babe305e
- ec66400775028485e4d3fbcf8d3f0b84578edd52

**Comment by glours** [comment]
Hello @otkd 
Thanks for catching this and reporting this issue. 

This wasn't expected and it's related to a misconfiguration following a change of laptop. 
As you may notice @aevesdocker was properly signing [their commits](https://github.com/compose-spec/compose-spec/commit/fbaa7287450d6c1118cd3346e670742265ac212b) few weeks/months ago and none of the contributors noticed this involuntary change. 
So we don't need to change anything and @aevesdocker will update their git configuration to generate valid signoff commits.
