### ISSUE TITLE
This is wrong

### ISSUE THREAD

**Issue by adRn-s** [compose-spec/compose-spec#403]
The `networks:` example YAML says 'volumes' instead of networks:

```
volumes:
  db-data:
    driver: overlay
```

see: https://docs.docker.com/compose/compose-file/06-networks/#attributes

The whole section is rather confusing.

I think that I already found (thanks to StackOverflow) what I was looking for, the DNS `host.docker.internal`, which is barely mentioned in these docs btw. Maybe the whole section is up for some updates? Specially after https://github.com/docker/compose/issues/10797

**Comment by glours** [comment]
Fixed by https://github.com/compose-spec/compose-spec/pull/388
