### ISSUE TITLE
Contradiction in Compose Build Specification

### ISSUE THREAD

**Issue by ermartinez13** [compose-spec/compose-spec#457]
**What is the problem you're trying to solve**

In the Compose Build Specification (eg. `/build.md`) the following statements are found: 

A) "When a build subsection is present for a service, Compose ignores the image attribute for the corresponding service, as Compose can build an image from source."

B) "When a service definition includes both the image attribute and a build section, Compose can't guarantee a pulled image is strictly equivalent to building the same image from source. Without any explicit user directives, Compose with build support first tries to pull the image, then builds from source if the image is not found on registry. Compose may offer options to customize this behaviour by user request."

From my perspective, it appears statements A and B are contradictory to each other. Perhaps there is something I may be misunderstanding or some missing piece of context?

**Describe the solution you'd like**

A definitive statement on the relationship between the image and build attributes when both are present.

**Additional context**

Statement A is found under the [Definitions](https://github.com/compose-spec/compose-spec/blob/master/build.md#definitions) section while statement B is found under the [Consistency with image](https://github.com/compose-spec/compose-spec/blob/master/build.md#consistency-with-image) section.

**Comment by thernstig** [comment]
https://github.com/docker/docs/issues/18887 :D
