### ISSUE TITLE
Spec does not allow an array of anchors (but should)

### ISSUE THREAD

**Issue by bmerigan** [compose-spec/compose-spec#474]
**What is the problem you're trying to solve**
Reusable sections of code [fragments](https://github.com/compose-spec/compose-spec/blob/master/10-fragments.md) and [extensions](https://github.com/compose-spec/compose-spec/blob/master/11-extension.md) are defined in the spec, but the spec does not actually allow the use of 2 or more fragments in the same service definition.  
This [closed Docker issue](https://github.com/docker/compose/issues/10824), confirms it should be of the form `<<: [*first, *second]` as already shown in the [extensions](https://github.com/compose-spec/compose-spec/blob/master/11-extension.md) doco examples.  
`compose-spec.json` does not list `array` as an allowed child of the environment object (line 828)  
```
    "list_or_dict": {
      "oneOf": [
        {
          "type": "object",
          "patternProperties": {
            ".+": {
              "type": ["string", "number", "boolean", "null"]
            }
          },
          "additionalProperties": false
        },
        {"type": "array", "items": {"type": "string"}, "uniqueItems": true}
      ]
    },
```

**Describe the solution you'd like**
The spec needs to accept the syntax: `<<: [*first, *second, *third, ...]`  as shown in [extensions](https://github.com/compose-spec/compose-spec/blob/master/11-extension.md) doco  
Edit compose-spec.json line 828 to: `"type": ["array", "string", "number", "boolean", "null"]`

**Additional context**
My IDE currently highlights these lines as invalid even though they are, and my investigation has led me to this repo being the source of truth.
![image](https://github.com/compose-spec/compose-spec/assets/11011615/641094c9-796d-48c7-a148-4e1233e19929)

**Comment by ndeloof** [comment]
yaml anchors is a pure yaml syntax feature, this is not modeled by compose-spec.json
This sounds like a bug/limitation in your IDE with yaml edition

**Comment by bmerigan** [comment]
I need you to explain that further if you could.  Are you saying a docker-compose.yaml file should NOT reference compose-spec.json?

**Comment by ndeloof** [comment]
docker-compose.yaml SHOULD refer to compose-spec.json, but this json schema defines the data tree t validate, while yaml syntax allows more, including use of anchors. It seems your IDE does not manage yaml anchors, while this is well defined by the yaml language spec (https://ktomk.github.io/writing/yaml-anchor-alias-and-merge-key.html)

Which IDE is this ?

yaml with anchors -> yaml parsing -> yaml node tree -> json schema validation

**Comment by bmerigan** [comment]
This is in Jetbrains PHPStorm.
Thanks for the explanation

**Comment by ndeloof** [comment]
Weird... I'm using Golang which has very good support for compose file edition, and I don't have such an issue

I guess the error is that you use anchors to a declaration that is set _later_ in your compose.yaml file, should be declared _before_ any reference . The json validation pop-up is confusing here but unrelated to the actual error reported on merge keys

**Comment by bmerigan** [comment]
I have them declared at the start of the file, then used in multiple places throughout the file.  Won't be related to that.  

example:  
```
version: '3.7'

x-composer: &composer
  COMPOSER_FOO: fff
  COMPOSER_BAR: ggg

x-feature-flag: &feature-flag
  FF_QUX: hhh

x-apm: &apm
  APM_BAZ: ppp

services:
  my-service-name:
  ...
    environment:
      FOO: xxx
      <<: [*composer, *feature-flag, *apm]
      BAR: yyy
```

**Comment by ndeloof** [comment]
remove `version: '3.7'` from your compose file. This is obsolete, and (while there's no reason for this) this seems to change the way Jetbrains IDE parse and validate the compose file
