### ISSUE TITLE
compose-spec.json does not contain Replace Value tags (from Docker Compose 2.24.4)

### ISSUE THREAD

**Issue by inostia** [compose-spec/compose-spec#487]
**What is the problem you're trying to solve**
[schema/compose-spec.json](https://github.com/compose-spec/compose-spec/blob/master/schema/compose-spec.json) does not contain the `!override` tag as [documented here](https://github.com/compose-spec/compose-spec/blob/master/spec.md#replace-value).

**Describe the solution you'd like**
Add the [Replace Value](https://docs.docker.com/compose/compose-file/13-merge/#replace-value) tags available from Docker Compose version 2.24.4 to the [schema/compose-spec.json](https://github.com/compose-spec/compose-spec/blob/master/schema/compose-spec.json) file.

**Additional context**
This is causing VSCode to render an error with "Unresolved tag":
<img width="789" alt="image" src="https://github.com/compose-spec/compose-spec/assets/14210438/39492640-960b-4d56-ad0a-a456d2441bb0">

**Comment by emilpaw** [comment]
@inostia I'm running into the same issue. What was your misunderstanding?
