### ISSUE TITLE
Call for maintainers 

### ISSUE THREAD

**Issue by nebuk89** [compose-spec/compose-spec#57]
Hey All,

Since the Compose Specification is now being handed over to the community there are a lot of potential changes that have been proposed already and we suspect more coming as people start to get involved.
To help manage these and support the growing community we are looking for about 3 maintainers of the Compose Specification. 

We request developers who use and love Compose today, who have experience building developer tooling and prefer those who have previous experience working on Open Source Specifications previously. Experience working with Compose outside of local development is also preferred with users of Compose on K8s, Kompose or services like ECS a plus.  
For all considering being maintainers having an interest in how to optimize the Compose format for developers locally while not overloading it or just rebuilding KubeYaml is a must. Compose is loved as it is lightweight and simple to use - we all need to maintain this going forward.

Maintenance entails:

- Responding to new issues
- Supporting fortnightly community discussion
- Being active and engaged on the Slack channel
- Supporting wider initiatives such as submissions to Open source foundations 
- Optionally, adding new features or suggestions of your own!

If you wish to request being a maintainer then please drop a message on the [Compose Specification slack channel ](https://cloud-native.slack.com/archives/C01162AJ23C) on the [CNCF Slack](https://slack.cncf.io). 

If you are unsure feel free to ask more questions here.

**Comment by vsoch** [comment]
I’m not sure how I can help, but I love Docker compose, have used it for many years (albeit mainly locally) and maintain https://github.com/singularityhub/singularity-compose for Singularity containers, which after the development here, I will look into if we can have 100% conformance (Singularity doesn’t have Dockerfile so you can imagine that is missing, and I added a few config options specific to Singularity). Let me know if you think I could be of help!

**Comment by justincormack** [comment]
@vsoch it would be great if you could document in an issue (maybe a PR, although we don't currently have anywhere to put it!) the specific config options you have added and what you do not support and why. We would like to collect together all the issues implementors have had, and see if there is commonality in things that are or are not supported.

**Comment by OneCricketeer** [comment]
Looking forward to the future of this project! 

Already started a decent working stack of software over here 

- https://github.com/OneCricketeer/gryllidae
- https://www.reddit.com/r/docker/comments/gbov88/use_docker_compose_frustrated_with_linking_a/

+ I'm still learning Golang, so also hopeful for integrating something around <https://github.com/compose-spec/compose-go>
