### ISSUE TITLE
Add support for `device_cgroup_rules`

### ISSUE THREAD

**Issue by agners** [compose-spec/compose-spec#62]
**What is the problem you're trying to solve**
The Docker container engine offers the `--device-cgroup-rule` option to add devices to allowed devices list. This is very helpful if hardware needs to be accessed from within the container to make sure only a minimal set of hardware is accessible (helps to avoid the use of `--privileged`).

**Describe the solution you'd like**
In Docker Compose format 2.3 and later this has been part of the Docker Compose spec. I would like to readd this field to the latest version of the Docker Compose spec.

**Additional context**
This is a "Container runtime configuration", which in turn is part of "Deploy" area and as defined in the VISION.md document, this area is in scope of Compose.

The `device_cgroup_rules` as specified in Compose v2 reference:
https://docs.docker.com/compose/compose-file/compose-file-v2/#device_cgroup_rules

**Comment by ndeloof** [comment]
Generaly speaking I'd like we re-introduce all v2 attributes removed by v3
(see https://github.com/compose-spec/compose-spec/issues/12)
Maybe `extends` would have much impacts and should first be excluded from this

**Comment by agners** [comment]
Fine for me, as long as it does not block/delay inclusion into the spec :-)

**Comment by Toasterson** [comment]
Could we leave out cgroup in the name? illumos device delegation is not cgroups based but I would like to use this feature for the same use case. Including cgroups would confuse our users.

**Comment by ndeloof** [comment]
@Toasterson if we do we will have to introduce both, maybe as an alias, as `device_cgroup_rules` is a legacy attribute

**Comment by Toasterson** [comment]
Ah I see your goal now. I'm fine with having it in the spec as a legacy attribute. For the future an alias or a vendor neutral spec will better fit the goals. Looking at the speed you want to get v2 back in we best proceed with this now and look at more generic rules later.

**Comment by agners** [comment]
@Toasterson FWIW, dropping cgroup sounds reasonable to me, but like you suggest in a second step.

Also note that the current format comes exactly from what the cgroup v1 device controller needs, I guess that is why cgroup ended up in the name. But in cgroup v2 BPF needs to be used to achieve the same. Towards the user the old interface can be maintained of course, but at that point the device rule format really becomes just an API spec rather than something cgroup specific.

**Comment by Toasterson** [comment]
Then we will need to look over it in any case once we get to add support for cgroup v2. LGTM from me.
