### ISSUE TITLE
Include an archived version of fig.sh website

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#66]
**What is the problem you're trying to solve**
We need to remember where we come from as part of specification history

**Describe the solution you'd like**
include an archived version of legacy fig.sh website

**Additional context**

**Comment by bfirsh** [comment]
Yessss!

https://github.com/orchardup/fig.sh

It is still served by GitHub pages at http://orchardup.github.io/fig/ . Before I left Docker, I set up a free Cloudflare account to do the SSL termination, in the hope that nobody would switch it off if it wasn't costing anything. :)

Funnily, looking at Cloudflare logs, fig.sh stopped working at exactly the time Docker Enterprise got acquired. Clearly somebody did some due diligence on all the domains that Docker owned and switched it off.

**Comment by bfirsh** [comment]
Ah -- I managed to get the GitHub page working again by removing the custom subdomain. http://orchardup.github.io/fig/ seems to work now!

**Comment by bfirsh** [comment]
It occured to me if you know who manages the domains at Docker, maybe we can get the old fig.sh domain working. :D

**Comment by OneCricketeer** [comment]
If Cloudflare doesn't work out, Netlify or Zeit are great options

**Comment by ndeloof** [comment]
Or just plain GitHub pages...kiss ;)
