### ISSUE TITLE
Support condition: service_healthy from v2

### ISSUE THREAD

**Issue by EricHripko** [compose-spec/compose-spec#68]
**What is the problem you're trying to solve**
We use Docker primarily for developing locally and running integration/system
tests on CI. This approach works brilliantly for us, as `docker-compose.yaml`
wholly describes the runtime environment needed to run an application. However,
we have a tough time dealing with the readiness problem. It's not enough to
just start the Compose services in the right order, as some infrastructure
takes time to become ready to serve the requests.

This negatively affects the experience with `docker-compose`, both when working
locally and, especially, when designing CI tests. This is because the 'naive
approach' of only using `depends_on` leads to a race condition by default. Such
tests will succeed if infrastructure comes up in time, and fail otherwise. 
Developers quickly learn to disregard flaky tests, at which point these are as
useful as having no tests.

**Additional context**
The general stance on this from Docker folks seems to summarised in 
[Startup order](https://docs.docker.com/compose/startup-order/) docs page:

> Your application needs to be resilient to these types of failures. To handle
> this, design your application to attempt to re-establish a connection to the
> database after a failure. If the application retries the connection, it can
> eventually connect to the database.

While the sentiment is definitely positive, I disagree with tightly coupling
readiness with resilience against network loss. An app can be resilient, but
choose to do sanity checks at startup. For example, a service could check if
a database is available at startup and, if it's down, exit out immediately.
This will cause the supervisor to restart the service and, eventually, begin
alarming to let SREs know that something is wrong. In my opinion, this approach
is just as valid as having the service remain in 'starting' state until the
database is available.

What is more, this seems to be a very deployment-oriented advice. If you use
`docker-compose` for working locally or CI, you probably just want the
containers to be ready and aren't too worried about resilience.

All of the workarounds suggest injecting some form of 'wait' script into the
command or entry-point. While this works for simpler setups, it doesn't really
scale well:

- __Duplication__ - dependencies are now listed in both `depends_on` and the
  wait script(s). Additionally, wait scripts now have to be (more or less)
  duplicated in all projects using `docker-compose`.
- __Leaky abstraction__ - developers now have to know how to check if a
  particular bit of infrastructure is ready (e.g., is it TCP? what's the port?
  is it HTTP? what URL should I check?). This becomes increasingly difficult in
  CI situations, where the database/cache/queue is pre-populated with data for
  reproducible tests (since just checking a port is no longer enough).
- __More dependencies__ - additional software is now required inside the app
  container. This degrades the overall UX from using Docker, as images are now
  larger and take longer to rebuild/download. In an anecdotal example, why
  should developers install several scripting interpreters just to check if
  dependencies are ready?
- __Complexity__ - each individual wait script needs to implement functionality
  that `healthcheck` already provides: initial delay, retrying and eventual
  timeout.

**Describe the solution you'd like**
I believe that `condition: service_healthy` is a suitable and very elegant
solution to this issue. It would be great to carry it over from _version 2_ of
compose to the newer versions of the format.

It doesn't suffer from the same issues that the workarounds have:

- There is a __single source of truth__ when it comes to container dependencies
  (i.e., `depends_on` in the `docker-compose.yaml`).
- __Separation of concerns__ - infrastructure containers are
  responsible for performing health checks on themselves and indicating
  readiness for the main app container.
- __Works out-of-the-box__ - no additional software has to be installed in
  the app container in order to 'wait' for dependencies.
- __Simplicity__ - opting in for readiness is as easy as setting
  `condition: service_healthy` for your service.

**Comment by OneCricketeer** [comment]
Personally, I have no issue with current solutions like `dockerize` or `wait_for_it`

**Comment by EricHripko** [comment]
Thank you for chipping in 👍 How do you deal with the shortcomings of these workarounds? I would especially love to hear about the case of pre-populating data for tests.

**Comment by OneCricketeer** [comment]
> pre-populating data for tests

Why is that the responsibility of compose? An entrypoint and/or volume mount work fine.

**Comment by OneCricketeer** [comment]
btw https://docs.docker.com/compose/startup-order/

**Comment by EricHripko** [comment]
This is where the _complexity_ drawback of these workarounds comes to light. The only reason that `mysql` image can work with `wait-for` (and alternatives) is because it spins up a whole temporary instance of the database just to populate the data. This is not trivial for some database technologies and, as far as I understand, doesn't work at all for in-memory caches and queues.

Thank you for linking the _Startup order_ page, this is the exact same page I reference in _Additional context_ section that specifically describes the issues we've faced with `wait-for` workarounds.

**Comment by OneCricketeer** [comment]
> spins up a whole temporary instance of the database just to populate the data

Really? That is new to me. 

If it is temporary, then why does it persist when actually using the database at app runtime?

> doesn't work at all for in-memory caches and queues

Like I said, volume mounts... Put a file in, up to the actual container's entrypoint to process that data in whatever format they want to. The container shouldn't return a healthy healthcheck until that "cold start" is completed. 

I still stand by the fact that it is up to the image's entrypoint+cmd, not compose to make this work

**Comment by EricHripko** [comment]
Both temporary and final instance use the same path on disk, which is how data persists - at least in case of MySQL entry point you linked earlier on.

Could you please elaborate which container in your scenario is responsible for importing the data? Is it the main/application one or is it the infrastructure one? How would the container indicate a healthy health-check here?

**Comment by OneCricketeer** [comment]
> Both temporary and final instance use the same path on disk

Interesting. Still not sure I understand why one database cannot remain active. That is how you'd do it on actual server, when restoring from mysqldump

---

> which container in your scenario is responsible for importing the data

Either an `InitContainer` (which your app `depends_on`) and polls when given a certain flag, or the "data"(base) container itself using some system similar to the MySQL one. I don't have much examples - I use Hadoop/S3 and Kafka a lot lately, and Kafka topics are just stored as JSON blobs in Zookeeper, so really easy to write an init-script for those

**Comment by EricHripko** [comment]
MySQL entry-point works in the following way:
- A temporary instance is started with Unix socket as the only interface
- Data import is performed using the Unix socket
- Final runtime instance is started on port 3306
- At this point, wait-style workarounds signal readiness (since port 3306 is reachable)
- Your app/test suite starts

As you pointed out, one instance could be used; this would lead to the following:
- Final runtime instance is started on port 3306
- At this point, wait-style workarounds signal readiness (since port 3306 is reachable)
- Your app/test suite starts
- Data import finishes some time later

As you can see, the wait script approach completely breaks down in the second case. This is exactly what I’m referring to in the _Additonal context_ section of my original post. The Kafka image you linked [creates topics](https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L22) after the Kafka is started on the public port. This means that you’re relying on a race condition (topic creation completing before your app needs to use them). I’ve discussed this in detail in my original post. In my opinion, this just further highlights why having `condition: service_healthy` is necessary.

**Comment by EricHripko** [comment]
I don’t quite see how having an init container solves the problem at hand. This adds complexity (at least one extra container is needed), but only kicks the can down the road (how does the app container know that init container completed?).

**Comment by OneCricketeer** [comment]
Alright, my bad for just trusting how the mysql container works (I very rarely use it anyway, and haven't had a problem). My stacks usually involve using MariaDB, Postgres, Elasticsearch, Neo4j, Redis...

> you’re relying on a race condition ([Kafka] topic creation completing before your app needs to use them)

That's true, but that's an O(1) operation into Zookeeper, and app startup is commonly much longer.

> only kicks the can down the road (how does the app container know that init container completed?)

That would have to be programmed in with some callback interface. 

Overall I'm thinking nothing should be blocking, if possible. Plus, there's a difference between 'ready' and 'healthy', while Compose seems to currently be focused on 'running' and 'healthy' (assuming people actually add healthcheck clause)

**Comment by EricHripko** [comment]
Unfortunately, relying on race conditions doesn’t work well - especially in CI world. We’ve had plenty of situations where populating data/configuring dependency didn’t complete in time.

I do agree that there is a difference between between ‘ready’ and ‘healthy’, but it’s a much larger discussion. Neither `docker` nor `docker-compose` have a concept of readiness at the moment, so this would require broad changes in the daemon, CLI and Dockerfile syntax.

Differentiating between these two states could be a further evolution of this proposal, for example via `condition: service_ready`.

**Comment by ndeloof** [comment]
Seems I forgot about this one on https://github.com/compose-spec/compose-spec/issues/12, but IMHO such a legacy v2 attribute should be part of the spec, even if only a few implementations/platforms can actually support this feature.

**Comment by EricHripko** [comment]
When it comes to the case we discussed above (pre-populating some containers with dev/test data), I think it's a clear gap in the v3 functionality. While `condition: service_healthy` may be considered legacy, it fills this gap perfectly without introducing complexity.

It's evident that this is a problem that needs to be solved - as we see other orchestration tools having functionality targeted at addressing this. For example, it looks like [init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) is the answer for Kubernetes (Pod doesn't go into `Ready` state until init containers complete).

**Comment by ndeloof** [comment]
closed by https://github.com/compose-spec/compose-spec/pull/72
