### ISSUE TITLE
Add support for `ipc: service` syntax

### ISSUE THREAD

**Issue by EricHripko** [compose-spec/compose-spec#70]
**What is the problem you're trying to solve**
`docker` supports `--ipc` flag, which according to [docs](https://docs.docker.com/engine/reference/run/#ipc-settings---ipc):
> Shared memory segments are used to accelerate inter-process communication at memory speed, rather than through pipes or through the network stack. Shared memory is commonly used by databases and custom-built (typically C/OpenMPI, C++/using boost libraries) high performance applications for scientific computing and financial services industries. If these types of applications are broken into multiple containers, you might need to share the IPC mechanisms of the containers, using "shareable" mode for the main (i.e. “donor”) container, and "container:<donor-name-or-ID>" for other containers.

Assuming I have an application that makes use of shared memory, I can bring it up with `docker run --ipc=container:name ...`. All good here 👍 

However, if I'm using `docker-compose` - I am unable to get the same behaviour. This is because, according to [docs](https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir), it's simply a pass-through option. This forces developers to co-host everything in the same container, which is difficult to work with and doesn't scale. 

**Describe the solution you'd like**
It would be amazing if `ipc` option in `docker-compose` supported `service:[service name]` syntax, similar to [network_mode](https://docs.docker.com/compose/compose-file/#network_mode). For example:
```
version: '2.4'
services:
  myrtr:
    image: myipcrouter
  mysvc:
    build:
      context: .
      dockerfile: Dockerfile
    ipc: service:myrtr
```
This would make the container for the service (i.e, mysvc) have `--ipc=container:<id of myrtr>`.

**Additional context**
Original issue submitted here https://github.com/docker/compose/issues/7220, PR for implementation is available here https://github.com/docker/compose/pull/7417. @ndeloof suggested an issue/PR is submitted here as well.

**Comment by Toasterson** [comment]
Shared Memory as IPC is not Supported in other Operating systems than linux. At least illumos I know does not due to Architectural design decisions. We consider applications which need such a fast interconnect as one Process in a Multiprocess architecture. 

Suggestions for handling:
1. Allow the engine to merge the containers into one native primitive with appropriate mechanisms applied (Chroot inside the Zone in my case)
2. Make this optional and have a mechanism to tell the application. That the container supports shared memory or not.
3. Leave as is and accept, that it's use will be limited to linux docker only.

Also, what about other IPC methods like Kernel IPC, Unix sockets and FIFO? Will they be blocked from inclusion by this and never make it in?

**Comment by EricHripko** [comment]
`ipc` setting controls access to [SysV IPC](https://en.wikipedia.org/wiki/Linux_namespaces#Interprocess_Communication_(ipc)). It's not responsible for isolation of any other IPC mechanism. As far as I'm aware, SysV IPC is supported on many other [Unix/Unix-like systems](https://en.wikipedia.org/wiki/Shared_memory#Support_on_Unix-like_systems) in addition to Linux. Some prominent examples include [Solaris](https://docs.oracle.com/cd/E19683-01/806-4125/svipc-41256/index.html) and [AIX](https://developer.ibm.com/technologies/systems/articles/au-spunix_sharedmemory/).

It's indeed not supported by Windows (which I believe) is the only non-Linux platform for `docker-compose`. However, I feel like this is part of a wider conversation since `ipc` setting is already in the spec and I assume `docker-compose` handles this case.

**Comment by Toasterson** [comment]
It's in the spec as the property exists but not what it does. Thus, Containers using this field are not portable.

**Comment by ndeloof** [comment]
Right, and many such attributes are not portable to various platforms, this is acknowledged by the spec and not required for a Compose Implementation to support everything from the spec (neither docker-compose nor swarm do!). In compose-spec, everything is optional, implementations which can't handle an attribute or syntax SHOULD warn the user and MAY just ignore it.
IMHO considering Linux kernel is a major citizen in the container ecosystem, and we already do for comparable attributes, this proposal is valuable.

**Comment by Toasterson** [comment]
Ah I seem to need to re read the spec again when I am not distracted. Sorry about the noise. Carry on.
