### ISSUE TITLE
Clarify spec intent in Vision docs regarding implementations

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#75]
**What is the problem you're trying to solve**
`VISION.md` should make it clear we don't expect any Compose implementation to support **all** attributes. Actually neither docker-compose not docker swarm do support everything set by compose v3.8 file format.

**Describe the solution you'd like**
A clear explanation for the specification to make attributes optional and define recommended behaviour for unsupported features.

**Additional context**
Discussed during community meeting on May 7th

**Comment by EricHripko** [comment]
This seems to have been addressed by the addition of [Requirements and optional attributes](https://github.com/compose-spec/compose-spec/blob/master/spec.md#requirements-and-optional-attributes) section to the spec in [your PR](https://github.com/compose-spec/compose-spec/pull/82). Should we close this as a result?
